### ISSUE TITLE
Crash while updating to version 1.1.1

### ISSUE THREAD

**Issue by Akava2005** [LeonBlade/PaisleyPark#1]
While updating Paisley Park from version 1.0.1 to 1.1.1, the application becomes unresponsive and can cause Final Fantasy XIV to crash.

Steps involved:

1. Ensure FFXIV is running 
2. Open Paisley Park (Version 1.0.1)
3. Accept the update (to Version 1.1.1)

An error will appear from ffxiv_dx11.exe and the client -may- crash.
Screenshot of error is below:

![PPark Error](https://user-images.githubusercontent.com/22595362/55686204-da238880-5923-11e9-9f9d-b7bf79a74e76.PNG)

**Comment by LeonBlade** [comment]
Thanks, I’ll look into this. Does the application work after updating okay?

**Comment by LeonBlade** [comment]
I've made some adjustments to the updater in aaf12fbf7281a6213c0dfc7086cc5e06b75c9aaa which may have fixed the issue.
