### ISSUE TITLE
PaisleyPark Won't Start

### ISSUE THREAD

**Issue by Kyitrai** [LeonBlade/PaisleyPark#12]
I'm not sure what started happening, but PaisleyPark will no longer fully run.

I was using 1.4.2 and then it suddenly stopped working. I updated to the most recent release - 1.4.5 - but the same behavior happens there. I'm not sure if this could have been from a recent windows update, as I haven't done much else to my PC.

When I run the program, it promotes to Administrator mode, spawns the updater (which says it's up to date), and then the program closes. When deleting the settings file it will ask to download the offsets, but still doesn't stay running after that. This is with ACT and/or FFXIV running and not running.

There's nothing added to `error.log`, and the only content for `output.log` is:
```
2019-09-26 17:52:02.9109|INFO|PaisleyPark.ViewModels.MainWindowViewModel|--- PAISLEY PARK START ---
2019-09-26 17:52:02.9339|INFO|PaisleyPark.ViewModels.MainWindowViewModel|Fetching update.
```

Let me know if there's any other information I can provide.

**Comment by LeonBlade** [comment]
Have you done anything else on your system lately that would cause this to happen?

**Comment by Kyitrai** [comment]
Aside from Windows Updates (Win10 btw), not that I can recall.

**Comment by LeonBlade** [comment]
Can you check and see if there are any logs in the Event Viewer related to Paisley Park?

**Comment by Kyitrai** [comment]
Ah, there are entries there. Here's the most recent event:

```xml
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
    <System>
        <Provider Name="Application Error" />
        <EventID Qualifiers="0">1000</EventID>
        <Level>2</Level>
        <Task>100</Task>
        <Keywords>0x80000000000000</Keywords>
        <TimeCreated SystemTime="2019-09-26T23:52:03.337360400Z" />
        <EventRecordID>3057</EventRecordID>
        <Channel>Application</Channel>
        <Computer>SLIPSTREAM</Computer>
        <Security />
    </System>
    <EventData>
        <Data>PaisleyPark.exe</Data>
        <Data>1.4.5.0</Data>
        <Data>8d3a0b56</Data>
        <Data>d3d9.dll</Data>
        <Data>10.0.18362.329</Data>
        <Data>1ac9a115</Data>
        <Data>c0000005</Data>
        <Data>00000000000ac44e</Data>
        <Data>3e58</Data>
        <Data>01d574c564c9da52</Data>
        <Data>C:\Users\Kyitrai\Documents\PaisleyPark\PaisleyPark.exe</Data>
        <Data>C:\Windows\SYSTEM32\d3d9.dll</Data>
        <Data>35998dc0-d198-49b1-b671-71fa625252f1</Data>
        <Data />
        <Data />
    </EventData>
</Event>
```

The target being `d3d9.dll` made me realize RivaTuner might be in the way since it hooks that (I use it especially on games that don't do frame limiting well, like FFXIV :P). It was been enabled to hook globally (which I think has always been the case, but a bit fuzzy there). So I disabled that, and now it's fine.

Thanks for your prompt replies!

**Comment by LeonBlade** [comment]
There is a build I have that fixes this, but it's not pushed out yet.  You can download it here: https://cdn.discordapp.com/attachments/578011246293549072/622467530065313792/PaisleyPark.zip

**Comment by Kyitrai** [comment]
Nice - just tried it; re-enabled RivaTuner and started it, seems to be happy!

Thanks again!
