### ISSUE TITLE
there is a problem loading your current position

### ISSUE THREAD

**Issue by linflyanfang** [LeonBlade/PaisleyPark#13]
[error.log](https://github.com/LeonBlade/PaisleyPark/files/4052257/error.log)
[output.log](https://github.com/LeonBlade/PaisleyPark/files/4052258/output.log)

Paisley park does not function and crushes the game whenever I try to load waymarks

downloaded and extracted to desktop. Opened ffxiv normally. Not sure what went wrong

**Comment by LeonBlade** [comment]
You are having issues with downloading the latest offsets.  Please download them manually from [here](https://raw.githubusercontent.com/LeonBlade/PaisleyPark/master/Offsets/2019.12.19.0000.0000.json) and renaming the file to `Offsets.json` in your Paisley Park folder.
