### ISSUE TITLE
Chinese server offsets

### ISSUE THREAD

**Issue by YuanxunTao** [LeonBlade/PaisleyPark#18]
Where can I get offsets for CN server? Tried all offsets in Offsets folder but none of them works for CN server.

**Comment by LeonBlade** [comment]
You'd have to ask BlueFissure in the Discord.

**Comment by LeonBlade** [comment]
Here, they have their own page for it: https://file.bluefissure.com/FFXIV/

**Comment by YuanxunTao** [comment]
Thanks a lot, it works now
