### ISSUE TITLE
Triggering presets using in-game chat log/macros?

### ISSUE THREAD

**Issue by XephyLon** [LeonBlade/PaisleyPark#2]
Loving the app by the way, but I was wondering if it's possible to make it so that it responds to chat log. Kind of like how ACT responds to `/e end` for example. But for activating presets.

Thanks in advance.

**Comment by LeonBlade** [comment]
Glad to see you're enjoying the app.  I do have this feature in mind.  The current feature in progress is connecting the app with Cactbot and Triggernometry.  I'll also try to include functionality for the chat input as well with this release.

**Comment by Bluefissure** [comment]
AFAIK Triggernometry can call other application(s) in a trigger, so maybe a PaisleyPark.cmd which accept waymark json file(s) can be under consideration.
Moreover, a REST API can be convenient too, which is under Leon's development rn (according to commits about Nancy host).

**Comment by LeonBlade** [comment]
> AFAIK Triggernometry can call other application(s) in a trigger, so maybe a PaisleyPark.cmd which accept waymark json file(s) can be under consideration.
> Moreover, a REST API can be convenient too, which is under Leon's development rn (according to commits about Nancy host).

I talked to the creator of Triggernometry and they are working on supporting it through a REST request which is currently implemented in my personal development version of Paisley Park.

**Comment by LeonBlade** [comment]
A portion of this feature has been implemented, there are some docs on the Wiki here now how to do it.  The rest of these features I will get to at some point.

**Comment by Bluefissure** [comment]
Well, I'm thinking of adding another endpoint of API to load presets from file, instead of providing waymarks' position, like:
```
url: http://localhost:12345/load
data:
{
  "Preset": "O12S"
}
```
and then the plugin can load it from stored json file.
Just an enhancement of API, not that urgent lol ^ ^

**Comment by LeonBlade** [comment]
The latest release now allows you to save and load presets with the REST API which is documented [here](https://github.com/LeonBlade/PaisleyPark/wiki/REST-API).  With this, you can create a trigger to listen to `/echo` command or something else in order to place waymark presets.
