### ISSUE TITLE
1.3.9

### ISSUE THREAD

**Issue by MrSigy** [LeonBlade/PaisleyPark#7]
Keeps saying it's the old version 1.3.8
Application works fine just keeps trying to update itself even after updating.
Also text in application says it's 1.3.8 while it's the 1.3.9 version and markers work without a problem

**Comment by LeonBlade** [comment]
Sorry, I’m not home to do a proper update.  You can ignore the update for
now.

**Comment by LeonBlade** [comment]
Update 1.4.0 is the newest version and won't have this issue anymore.  Sorry for the inconvenience.
