### ISSUE TITLE
Can't update when inside folders with spaces in the name

### ISSUE THREAD

**Issue by Ihellmasker** [LeonBlade/PaisleyPark#8]
Hi there

I seem to be having an issue where if Paisley Park if the directory structure leading up to where the exe is have any spaces in the name then it will not update and it will create a new empty folder instead.

Example;

I store the app in `D:/GDrive/Games/Final Fantasy XIV/Apps/PaisleyPark`

this errors out when updating and will create a new folder

`D:/GDrive/Games/Final`

**Comment by LeonBlade** [comment]
I'm aware of this issue and will be fixing it when I get back home (on vacation).  It has to do with the updater and spaces in the path name.  You can download the latest release manually.

**Comment by Ihellmasker** [comment]
Yeah i've been doing that, just wanted to make sure you were aware of it :)

Great app tho, thanks for your work! You don't know how much I wished for something like this when having to setup markers through Stormblood, wish I knew about it sooner!

**Comment by LeonBlade** [comment]
I'm glad you're enjoying it, and I'm very sorry that there are these issues.  Thanks!

**Comment by LeonBlade** [comment]
There is a new updater, this should fix this problem.
